import type { CasePresentationPatch } from "../../packages/mystery-core/src/index.ts";

type FocusedCopy = Partial<Omit<CasePresentationPatch, "caseId" | "baseCanonicalHash" | "presentationRevision">>;

const answerTemplates = {
  yes: "是。现有来源支持这个前提；它只固定一层事实，不自动补全整条因果链。",
  no: "不是。现有记录足以排除这个前提。",
  partial: "部分成立，但这个问法把两个仍需分别证明的环节并在了一起。",
  invalid_premise: "前提不成立。请先拆开对象、时间或记录来源，再逐项验证。",
  unknown: "目前公开的来源不足以确认或否定。",
  irrelevant: "这件事可能为真，但不会改变当前异常的必要因果链。",
  unanswerable: "案件中没有可核对的来源回答这个问题。",
  unrecognized: "没有识别到明确的对象与关系；请换成一次只验证一个事实的问法。",
} as const;

export const V14_FOCUSED_COPY: Record<string, FocusedCopy> = {
  "c01-cold-room-knock": {
    title: "冷藏室的敲门声",
    surface: "凌晨两点，封闭的冷藏室里传出三下敲击。监控显示研究员一小时前已经离开，门禁也没有第二次进入记录。声音、门锁和失踪的样本之间，哪一条因果链能同时成立？",
    answerTemplates,
    questionLabels: {
      "query-person-inside": "敲击发生时，冷藏室里是否有人？",
      "query-knock-source": "三下敲击是否真的来自门内？",
      "query-door-mechanism": "这扇门关闭后会自动锁住吗？",
      "query-phone-inside": "敲击前，室内是否留有会震动的设备？",
      "query-lin-ownership": "留下的设备属于林澈吗？",
      "query-sample-location": "样本最后在哪里被找到？",
      "query-lin-motive": "延迟检查会让林澈获利吗？",
      "query-fang-entered": "锁门以后，有人再次进入过吗？",
      "query-irrelevant-color": "托盘的颜色会影响敲击机制吗？",
    },
    feedbackCopy: {
      "missing-time": "离开、自动上锁、定时震动和延迟检查还没有排成一条时间链。",
      "missing-space": "手机、托盘、门内与外部储物柜的位置关系仍未闭合。",
      "missing-source": "还缺一条能把敲击、设备和独立录音互相印证的来源链。",
      "missing-identity": "设备归属与执行安排还没有落到同一个人身上。",
      "missing-measurement": "三次等间隔震痕与录音中的三下敲击还没有相互校验。",
      "missing-state": "门关闭后的锁止状态与室内无人状态仍需同时成立。",
      "missing-alternative": "仍需用门禁或录音证据排除有人返场、值班员伪造这两条路径。",
    },
    evidenceCopy: {
      "evidence-cctv-exit": { title: "01:00 · 最后一次离开", observation: "楼层监控连续拍到林澈离开，之后没有拍到他返回冷藏室走廊。" },
      "evidence-door-latch": { title: "门框内侧的自动门闩", observation: "门一旦合拢就会自行卡住；所谓“从里面锁上”并不要求室内有人操作。" },
      "evidence-metal-tray-mark": { title: "托盘边缘的三处震痕", observation: "三处细小撞痕间距接近，方向都指向托盘下方同一位置。" },
      "evidence-phone-in-room": { title: "托盘下的定时手机", observation: "手机仍留在冷藏室，系统记录显示它在敲击时段触发过一次定时震动。" },
      "evidence-phone-pairing": { title: "设备绑定页", observation: "这部手机与林澈的研究终端使用同一账户完成配对。" },
      "evidence-knock-recording": { title: "走廊独立录音", observation: "固定录音器保存了三下短促敲击；它证明声音真实发生，不证明当时门内有人。" },
      "evidence-access-log": { title: "门禁与储物柜的交叉记录", observation: "门锁后没有再次开门，但外部储物柜在更早时段留下过样本盒的存取痕迹。" },
      "evidence-sample-locker": { title: "外部储物柜中的样本盒", observation: "失踪样本并不在冷藏室里，而是在门外的独立储物柜中被找到。" },
      "evidence-security-log": { title: "被推迟的开门检查", observation: "值班员相信门内有人，因而把强制开门检查推迟了二十五分钟。" },
      "evidence-intent-chain": { title: "敲击与延迟的闭合记录", observation: "设备布置、三下敲击、值班员误判与样本检查延迟在同一时间顺序上连续成立。" },
    },
    hypothesisLabels: {
      "hypothesis-canonical": "定时震动撞击托盘，敲击声让值班员延迟检查",
      "hypothesis-fang-entered": "方砚在锁门后重新进入并亲自敲击",
      "hypothesis-guard-faked": "值班员伪造了敲击录音与房间占用状态",
    },
    replayCaptions: {
      "replay-sample": "敲击发生以前，样本盒已经被转移到门外储物柜。",
      "replay-phone": "一部与林澈绑定的手机被留在金属托盘下，并设定了延时震动。",
      "replay-exit": "林澈离开后，门自动闭锁；门内不再需要有人。",
      "replay-knock": "定时震动推动手机撞击托盘，走廊录音留下三下敲击。",
      "replay-delay": "值班员把声音误判为有人求助，样本检查因此被推迟。",
    },
    evidenceVisualMode: "cold-room-forensics",
  },

  "c13-second-waterline": {
    title: "空杯里的第二条水线",
    surface: "量杯整夜没有开封，总质量也没有增加；清晨的液面却越过了第二条刻度。若没有人加液体，究竟是什么改变了水线？",
    answerTemplates,
    questionLabels: {
      "query-c13-01": "量杯的封膜被打开过吗？",
      "query-c13-02": "封存时的初始水线在哪里？",
      "query-c13-03": "夜里量杯周围升温了吗？",
      "query-c13-04": "固定配重的蜡扣会在这个温度软化吗？",
      "query-c13-05": "杯中的配重向下移动过吗？",
      "query-c13-06": "清晨配重是否完全浸入液体？",
      "query-c13-07": "新增排水体积能解释水线升高吗？",
      "query-c13-08": "封存前后整套装置的总质量变了吗？",
      "query-c13-09": "夜间记录里有人加过液体吗？",
      "query-c13-10": "蓝色标带会吸水或改变体积吗？",
    },
    feedbackCopy: {
      "missing-time": "升温、蜡扣软化、配重下沉和水线上升的先后仍未闭合。",
      "missing-space": "配重从液面上方到完全浸没的位置变化还没有落到量杯内部。",
      "missing-source": "封口、温度曲线和清晨照片尚未组成可追溯的来源链。",
      "missing-identity": "还没有确认移动的是配重，而不是液体本身或外来物。",
      "missing-measurement": "总质量、浸没体积和水线增量还没有放进同一个守恒关系。",
      "missing-state": "蜡扣从支撑到失效、配重从悬挂到浸没的状态变化仍缺触发条件。",
      "missing-alternative": "仍需用封口与总质量排除加液，并用排水复算排除单纯热膨胀。",
    },
    evidenceCopy: {
      "evidence-c13-01": { title: "未破损的封口边缘", observation: "显微照片中封膜连续，没有针孔、撕裂或重新热封留下的接缝。" },
      "evidence-c13-02": { title: "封存时的第一条水线", observation: "刻度相机在封存瞬间固定了液面位置，第二条水线当时尚未出现。" },
      "evidence-c13-03": { title: "恒温台夜间曲线", observation: "量杯所在台面整夜缓慢升温，并越过了固定蜡开始失去支撑力的区间。" },
      "evidence-c13-04": { title: "蜡扣材料说明", observation: "材料单说明这种固定蜡受热后会软化，但不会向杯中增加液体。" },
      "evidence-c13-05": { title: "导杆上的连续擦痕", observation: "擦痕从原固定点一直延伸到杯底，记录了配重沿导杆下沉的路径。" },
      "evidence-c13-06": { title: "清晨的浸没配重", observation: "清晨照片显示配重已完全位于液面以下，与封存时的悬挂状态不同。" },
      "evidence-c13-07": { title: "排水体积复算表", observation: "配重新增的浸没体积与液面升高所需体积相符。" },
      "evidence-c13-08": { title: "封存前后的总质量", observation: "两次称量的差值小于仪器误差，没有出现相当于新增液体的质量。" },
      "evidence-c13-09": { title: "夜班操作空白页", observation: "从封存到清晨，没有开盖、加液或更换量杯的操作记录。" },
      "evidence-c13-10": { title: "蓝色批次标带", observation: "标带只用于区分批次，不吸水，也不参与配重的固定和排水。" },
    },
    hypothesisLabels: {
      "hypothesis-canonical": "升温使蜡扣失去支撑，配重下沉并增加浸没排水体积",
      "hypothesis-c13-alternative-1": "有人从封口缝隙向量杯加入了液体",
      "hypothesis-c13-alternative-2": "液体受热膨胀独自造成了全部水线变化",
    },
    chapterTitles: { "chapter-c13-one": "封口未动，杯内状态却改变" },
    replayCaptions: {
      "replay-c13-1": "量杯以第一条水线封存，封膜连续完整。",
      "replay-c13-2": "恒温台缓慢升温，杯中总质量没有增加。",
      "replay-c13-3": "温度越过材料区间，固定配重的蜡扣逐渐软化。",
      "replay-c13-4": "配重沿导杆下沉，从悬挂状态变为完全浸没。",
      "replay-c13-5": "新增浸没体积排开液体，水线越过第二条刻度。",
      "replay-c13-6": "封口和总质量复核排除了外部加液，排水复算闭合了异常。",
    },
    evidenceVisualMode: "displacement-vessel-notes",
  },

  "c25-silent-second-bell": {
    title: "没有响起的第二次门铃",
    surface: "访客在十秒内按了两次门铃，按钮与控制器都留下两次触发；屋内录音却只有一次完整铃声。第二次按压去了哪里？",
    answerTemplates,
    questionLabels: {
      "query-c25-01": "按钮真的闭合了两次吗？",
      "query-c25-02": "控制器也累计了两次触发吗？",
      "query-c25-03": "屋内录音里到底有几次完整铃声？",
      "query-c25-04": "控制器会合并短时间内的重复触发吗？",
      "query-c25-05": "两次按压相隔多久？",
      "query-c25-06": "第二次按压时门铃处于什么状态？",
      "query-c25-07": "扬声器本身发生过故障吗？",
      "query-c25-08": "两次按压期间供电正常吗？",
      "query-c25-09": "住户听到的是两声，还是一段连续铃声？",
      "query-c25-10": "旧电池警告与这次少响一声有关吗？",
    },
    feedbackCopy: {
      "missing-time": "两次按压的间隔与防抖窗口还没有放在同一时间轴上。",
      "missing-space": "按钮、控制器和室内扬声器属于三个不同观测位置，仍需逐段连接。",
      "missing-source": "接点波形、控制器计数与室内录音尚未构成完整信号来源链。",
      "missing-identity": "触发记录与声学输出仍被当成了同一种事件。",
      "missing-measurement": "两次电平变化与一次声音包络的计数口径还没有分开。",
      "missing-state": "第二次触发发生时的 RINGING 状态与防抖保持条件尚未闭合。",
      "missing-alternative": "还需用按钮波形排除访客说谎，并用自检和供电排除扬声器故障。",
    },
    evidenceCopy: {
      "evidence-c25-01": { title: "按钮接点的双脉冲", observation: "示波波形保留了两次分离的接点闭合；访客确实按了第二次。" },
      "evidence-c25-02": { title: "控制器触发计数器", observation: "累计计数增加了两次，说明两次输入都到达了控制器。" },
      "evidence-c25-03": { title: "室内铃声包络", observation: "麦克风只记录到一段连续的完整铃声，没有第二个独立起音。" },
      "evidence-c25-04": { title: "十秒防抖参数", observation: "固件会把窗口内的重复触发归入当前响铃周期，而不是启动第二次输出。" },
      "evidence-c25-05": { title: "六点八秒的按压间隔", observation: "第二次接点闭合仍落在第一次响铃开启的防抖窗口内。" },
      "evidence-c25-06": { title: "RINGING 状态迁移", observation: "第二次触发到达时，状态机尚未从 RINGING 返回待机。" },
      "evidence-c25-07": { title: "扬声器事后自检", observation: "扬声器能够正常完成全频自检，没有支持“临时坏掉”的故障码。" },
      "evidence-c25-08": { title: "门铃供电曲线", observation: "整个窗口内电压高于最低工作阈值，声音没有因掉电中断。" },
      "evidence-c25-09": { title: "住户的连续铃声证词", observation: "住户描述的是一段从起音到结束都连续的铃声，而不是听漏了第二段。" },
      "evidence-c25-10": { title: "一个月前的旧电池警告", observation: "警告发生在电池更换以前，与本次两次触发合并没有时间关系。" },
    },
    hypothesisLabels: {
      "hypothesis-canonical": "两次触发都真实，但防抖窗口把第二次合并进当前响铃周期",
      "hypothesis-c25-alternative-1": "访客谎称自己按下了第二次按钮",
      "hypothesis-c25-alternative-2": "扬声器恰好在第二次按压时临时故障",
    },
    chapterTitles: { "chapter-c25-one": "两次输入，为什么只有一次输出" },
    replayCaptions: {
      "replay-c25-1": "第一次按压闭合接点，控制器开始一个完整响铃周期。",
      "replay-c25-2": "声音输出启动，十秒防抖窗口同时保持开启。",
      "replay-c25-3": "六点八秒后，第二次按压产生了另一条真实输入。",
      "replay-c25-4": "控制器登记触发，却因仍在 RINGING 状态而把它合并。",
      "replay-c25-5": "室内只形成一个连续声音包络，触发数与响铃数由此分离。",
      "replay-c25-6": "扬声器自检与供电曲线排除故障，旧电池警告只是无关记录。",
    },
    evidenceVisualMode: "debounce-signal-plates",
  },

  "c37-zeroed-pressure-gauge": {
    title: "回到零点的压力表",
    surface: "泄压已经完成，表针也回到了零位；同一管线随后用参考传感器复测，结果却与这只表不一致。表、压力和测量条件中，究竟哪一个变了？",
    answerTemplates,
    questionLabels: {
      "query-c37-01": "表针回零时，仪表零位仍可能偏移吗？",
      "query-c37-02": "这只表的零位需要随温度修正吗？",
      "query-c37-03": "管线当时确实完成泄压了吗？",
      "query-c37-04": "完整校准曲线是否带有偏置？",
      "query-c37-05": "独立参考传感器测到了非零压力吗？",
      "query-c37-06": "录像能确认表针确实指在零线上吗？",
      "query-c37-07": "常温校准卡给出的零点基准是什么？",
      "query-c37-08": "两次测量的环境温度相同吗？",
      "query-c37-09": "按温度修正后，两套读数能互相对应吗？",
      "query-c37-10": "传感器响应滞后能解释稳定后的固定偏差吗？",
    },
    feedbackCopy: {
      "missing-time": "泄压、回零、温度变化和复测还没有按发生顺序闭合。",
      "missing-space": "表针位置、管线压力与独立参考传感器的测量位置仍被混为一处。",
      "missing-source": "机械表录像、环境日志与参考传感器还缺一条交叉来源链。",
      "missing-identity": "仪表显示值、零位基准和真实压力仍被当成同一个量。",
      "missing-measurement": "零点修正、校准曲线和参考读数还没有进入同一个测量模型。",
      "missing-state": "从泄压状态到复测状态之间，温度改变零位的条件尚未闭合。",
      "missing-alternative": "还需用泄压回执排除残余压力，并用回零录像排除人为拨针。",
    },
    evidenceCopy: {
      "evidence-c37-01": { title: "冷态零位复核", observation: "机械表回到刻度零线时，零位与常温参考基准并未重合。" },
      "evidence-c37-02": { title: "温度补偿表", observation: "同一只表在不同环境温度下需要使用不同的零位修正。" },
      "evidence-c37-03": { title: "独立泄压回执", observation: "旁路压力源确认管线已经完成泄压，残余压力不能解释之后的读数差。" },
      "evidence-c37-04": { title: "全量程校准曲线", observation: "显示值相对参考压力呈带偏置的曲线；零点只是曲线上的一个位置。" },
      "evidence-c37-05": { title: "参考传感器复测", observation: "独立传感器在复测阶段记录到非零压力，与机械表的直读值不同。" },
      "evidence-c37-06": { title: "表针回零录像", observation: "录像确认指针确实落在零线上；它只证明指针位置，不证明真实压力为零。" },
      "evidence-c37-07": { title: "常温零压基准卡", observation: "常温校准时，机械零位与零压参考对齐，提供了可比较的起点。" },
      "evidence-c37-08": { title: "两次测量的环境日志", observation: "泄压检查与复测处在不同温度条件，不能共用未经修正的零位。" },
      "evidence-c37-09": { title: "修正后的复测对照", observation: "应用对应温度的零位修正后，机械表换算值重新接近参考传感器。" },
      "evidence-c37-10": { title: "响应时间试验", observation: "响应滞后只改变读数稳定所需时间，不能解释稳定后的固定偏差。" },
      "evidence-c37-11": { title: "回温后的第二次零检", observation: "环境恢复后零位偏差随之缩小，复现了偏移与温度的联系。" },
      "evidence-c37-12": { title: "外壳运输温度贴", observation: "变色贴只说明运输途中曾遇到低温，不参与本次复测的零位修正。" },
    },
    hypothesisLabels: {
      "hypothesis-canonical": "温度改变仪表零位，回零指针与真实压力因此不再等价",
      "hypothesis-c37-alternative-1": "压力仍被困在管线里，泄压其实没有完成",
      "hypothesis-c37-alternative-2": "有人把表针人为拨回了零线",
    },
    chapterTitles: { "chapter-c37-one": "先分开零位、显示值与真实压力" },
    replayCaptions: {
      "replay-c37-1": "管线完成泄压，机械表指针回到刻度零线。",
      "replay-c37-2": "环境温度改变了仪表自身的零位基准。",
      "replay-c37-3": "同一个指针位置因此对应了不同的修正后读数。",
      "replay-c37-4": "完整校准曲线把零位偏移与量程读数分开。",
      "replay-c37-5": "独立参考传感器证明复测阶段仍有非零真实压力。",
      "replay-c37-6": "应用温度修正后两套读数重新一致，残余压力和人为拨针均被排除。",
    },
    sceneAsset: "/assets/v14/c37-pressure-lab.svg",
    sceneAssetMobile: "/assets/v14/c37-pressure-lab-mobile.svg",
    evidenceVisualMode: "pressure-calibration-plates",
  },

  "c48-two-point-calibration": {
    title: "两个相同的校准点",
    surface: "仪器在量程两端都通过了校准，中间点却持续偏离参考值。两端都对，为什么中间仍然错？",
    answerTemplates,
    questionLabels: {
      "query-c48-01": "两个端点的校准记录都可靠吗？",
      "query-c48-02": "传感器响应可能是一条非线性曲线吗？",
      "query-c48-03": "中段偏差能够重复出现吗？",
      "query-c48-04": "中段参考值来自独立标准吗？",
      "query-c48-05": "加入第三个校准点后会暴露曲率吗？",
      "query-c48-06": "中段误差落在原先的不确定性带之外吗？",
      "query-c48-07": "线性模型和曲线模型都能穿过两个端点吗？",
      "query-c48-08": "中段读数仍在传感器量程以内吗？",
      "query-c48-09": "重复校准时两个端点仍然准确吗？",
      "query-c48-10": "残差表里的设备编号会改变曲线吗？",
    },
    feedbackCopy: {
      "missing-time": "首次两点校准、发现中段偏差和第三点复核的顺序仍未闭合。",
      "missing-space": "端点与中段在同一量程中的相对位置还没有落到曲线上。",
      "missing-source": "校准记录、独立参考值和重复测量还缺交叉验证。",
      "missing-identity": "端点准确与整条传递曲线准确仍被当成同一个命题。",
      "missing-measurement": "两个端点、第三点、残差和不确定性带尚未组成可辨识的测量模型。",
      "missing-state": "从两点线性假设切换到曲线模型的证据条件还没有满足。",
      "missing-alternative": "仍需用端点重复性排除记录错误，并用稳定残差排除中段偶发故障。",
    },
    evidenceCopy: {
      "evidence-c48-01": { title: "量程两端的原始校准单", observation: "低端与高端读数都与各自参考值一致，两个端点本身没有抄录错误。" },
      "evidence-c48-02": { title: "制造商的非线性响应页", observation: "传感器允许存在平滑曲率；仅凭两个端点无法确定端点之间的形状。" },
      "evidence-c48-03": { title: "可重复的中段偏差", observation: "中段读数在多次复测中向同一方向偏离，不像一次偶发跳变。" },
      "evidence-c48-04": { title: "独立中段参考值", observation: "参考值来自另一套可追溯标准，不依赖被测仪器自己的校准结果。" },
      "evidence-c48-05": { title: "新增的第三校准点", observation: "第三点落在线性连线之外，却落在允许的曲线响应上。" },
      "evidence-c48-06": { title: "原两点模型的不确定性带", observation: "观测到的中段偏差超过两点线性模型给出的允许范围。" },
      "evidence-c48-07": { title: "两种拟合模型对照", observation: "直线与曲线都能穿过两个端点，但只有曲线同时解释第三点。" },
      "evidence-c48-08": { title: "传感器有效量程表", observation: "异常中段仍位于额定量程内，不能用超量程饱和解释。" },
      "evidence-c48-09": { title: "端点重复性复核", observation: "重新校准后两个端点依旧准确，排除了端点记录偶然写错。" },
      "evidence-c48-10": { title: "按输入位置排列的残差", observation: "残差随输入位置平滑变化，支持模型形状错误而非中段突然损坏。" },
      "evidence-c48-11": { title: "反向量程端点检查", observation: "从高端向低端复测时，两个端点仍然重合，误差没有随操作方向消失。" },
      "evidence-c48-12": { title: "三点重建的传递曲线", observation: "加入第三点后重建出的曲线同时覆盖端点与中段参考值。" },
      "evidence-c48-13": { title: "校准单右下角的蓝色批号", observation: "批号颜色只用于区分纸本版本，不改变参考值、输入位置或拟合结果。" },
    },
    hypothesisLabels: {
      "hypothesis-canonical": "两点只能固定曲线两端，无法排除端点之间的非线性偏差",
      "hypothesis-c48-alternative-1": "其中一个端点被抄错，所谓校准通过并不真实",
      "hypothesis-c48-alternative-2": "仪器只在中段发生了偶发故障",
    },
    chapterTitles: { "chapter-c48-one": "两个正确端点不能决定整条曲线" },
    replayCaptions: {
      "replay-c48-1": "低端与高端分别校准，两处读数都准确。",
      "replay-c48-2": "系统默认用一条直线连接两个端点。",
      "replay-c48-3": "独立参考在中段复测，稳定偏差再次出现。",
      "replay-c48-4": "第三个校准点落在线性模型之外，暴露出响应曲率。",
      "replay-c48-5": "残差与不确定性带排除了偶发跳变和超量程。",
      "replay-c48-6": "三点曲线同时解释两端和中段：端点真实，模型不完整。",
    },
    sceneAsset: "/assets/v14/c48-curve-lab.svg",
    sceneAssetMobile: "/assets/v14/c48-curve-lab-mobile.svg",
    evidenceVisualMode: "curve-reference-plates",
  },

  "c60-last-sample-before-stop": {
    title: "终点前的最后一次采样",
    surface: "停止命令已经被系统确认；终端却在确认之后显示一条编号连续的新采样。命令、采集和显示，哪一个才真正发生在最后？",
    answerTemplates,
    questionLabels: {
      "query-c60-01": "停止命令确实被控制器接收了吗？",
      "query-c60-02": "命令到达前，缓存里已经有待发送样本吗？",
      "query-c60-03": "最后一条样本是在停止前采集的吗？",
      "query-c60-04": "采样器随后真的进入停止状态了吗？",
      "query-c60-05": "最后样本的序号与前一条连续吗？",
      "query-c60-06": "停止后发送队列仍会排空旧样本吗？",
      "query-c60-07": "停止回执后还有新的采集动作吗？",
      "query-c60-08": "采集时刻、发送时刻和显示时刻是否来自同一时钟？",
      "query-c60-09": "控制回路把命令确认和物理停止分开记录吗？",
      "query-c60-10": "终端主题或导出格式会改变样本顺序吗？",
    },
    feedbackCopy: {
      "missing-time": "采集、入缓存、停止命令、执行回执、发送和显示的顺序仍未闭合。",
      "missing-space": "采样器、环形缓存、发送队列与终端是四个不同位置，数据路径还缺连接。",
      "missing-source": "控制日志、样本头和终端接收记录尚未建立同一条来源链。",
      "missing-identity": "最后显示的记录与停止后新采集的样本仍被误认为同一个对象。",
      "missing-measurement": "采集时标、队列时标和终端时标还没有换算到同一时间基准。",
      "missing-state": "命令已接收、采样器已停止、缓存仍待发送三个状态尚未同时成立。",
      "missing-alternative": "仍需用执行回执排除命令失效，并用连续序号与来源链排除伪造。",
    },
    evidenceCopy: {
      "evidence-c60-01": { title: "停止命令接收回执", observation: "控制器确认收到停止命令；这证明命令进入系统，不代表所有缓存已清空。" },
      "evidence-c60-02": { title: "命令到达前的环形缓存", observation: "缓存快照中已经存在一条尚未发送的完整样本。" },
      "evidence-c60-03": { title: "最后样本的采集时标", observation: "样本头记录的采集时刻早于停止命令，终端显示发生在之后。" },
      "evidence-c60-04": { title: "采样器停止执行回执", observation: "控制回路随后确认采样器进入停止状态，命令并未失效。" },
      "evidence-c60-05": { title: "连续的样本序号", observation: "最后样本紧接前一条序号，没有插入、重写或伪造留下的断点。" },
      "evidence-c60-06": { title: "发送队列排空记录", observation: "停止采集后，发送器仍按规则送出了缓存中已经完成的样本。" },
      "evidence-c60-07": { title: "停止后的状态轨迹", observation: "停止回执以后没有新的采集边沿，只有队列和终端继续处理旧数据。" },
      "evidence-c60-08": { title: "三套时标对照", observation: "采集、发送与终端显示使用不同记录点；接收顺序不能替代采集顺序。" },
      "evidence-c60-09": { title: "命令—执行控制回路", observation: "系统把命令接收、物理停止和状态反馈分别记录，三者不是同一瞬间。" },
      "evidence-c60-10": { title: "终端最后一条显示记录", observation: "终端在停止确认后才收到并显示缓存样本，因此制造了“停止后采集”的表象。" },
      "evidence-c60-11": { title: "重复停止命令轨迹", observation: "重复发送停止命令没有产生新的采样，只返回已经停止的状态。" },
      "evidence-c60-12": { title: "缓存窗口配置", observation: "配置允许停止采集后继续排空已经封装的样本，不会生成新的测量。" },
      "evidence-c60-13": { title: "终端导出的绿色主题", observation: "界面主题只改变显示颜色，不参与采集、缓存、发送或时间排序。" },
    },
    hypothesisLabels: {
      "hypothesis-canonical": "停止前采集的样本留在缓存中，并在停止确认后才发送到终端",
      "hypothesis-c60-alternative-1": "停止命令没有生效，采样器继续工作",
      "hypothesis-c60-alternative-2": "终端最后一条样本是事后伪造的",
    },
    chapterTitles: {
      "chapter-c60-one": "第一阶段：先证明命令与采集边界",
      "chapter-c60-two": "第二阶段：沿缓存和发送队列追踪最后样本",
    },
    replayCaptions: {
      "replay-c60-1": "最后一条样本在停止命令到达以前已经完成采集。",
      "replay-c60-2": "样本被封装进环形缓存，却尚未发送到终端。",
      "replay-c60-3": "停止命令进入控制器，采样器随后完成状态切换。",
      "replay-c60-4": "执行回执确认停止生效，之后没有新的采集边沿。",
      "replay-c60-5": "最后样本保持连续序号，排除了插入或事后伪造。",
      "replay-c60-6": "发送器在停止后继续排空已有缓存。",
      "replay-c60-7": "终端较晚收到样本，于是在停止确认之后才显示它。",
      "replay-c60-8": "对齐采集、发送和显示时标后，每份记录都真实，异常来自把三个时刻当成一个。",
    },
    sceneAsset: "/assets/v14/c60-terminal-lab.svg",
    sceneAssetMobile: "/assets/v14/c60-terminal-lab-mobile.svg",
    evidenceVisualMode: "terminal-signal-plates",
  },
};

/**
 * Public discovery copy for the first scaffold of every generated case whose
 * original corpus starts with an authoring-template sentence. These labels do
 * not add match rules or change answer codes; they only replace the text shown
 * for an existing query id.
 */
export const V14_NATURAL_FIRST_QUESTIONS: Record<string, { queryId: string; label: string }> = {
  "c13-second-waterline": { queryId: "query-c13-01", label: "量杯的封膜被打开过吗？" },
  "c14-moving-red-box": { queryId: "query-c14-01", label: "箱子周围的粉尘圈有移动痕迹吗？" },
  "c15-sixth-panorama": { queryId: "query-c15-01", label: "合影里出现的是六个不同的人吗？" },
  "c16-closed-door-handoff": { queryId: "query-c16-01", label: "交接前后的密封袋编号是同一个吗？" },
  "c17-twelve-strikes": { queryId: "query-c17-01", label: "钟面指向十一点时，报时轮系也处于十一点吗？" },
  "c18-lighter-sealed-crate": { queryId: "query-c18-01", label: "箱子称重前，秤台已经完成归零吗？" },
  "c19-fog-after-window": { queryId: "query-c19-01", label: "关窗前，室内湿度已经接近露点了吗？" },
  "c20-fifth-worker": { queryId: "query-c20-01", label: "签到表记录的是独立人物，还是岗位？" },
  "c21-missing-seven-minutes": { queryId: "query-c21-01", label: "那七分钟里，录像系统仍按正常帧率采样吗？" },
  "c22-overloaded-bridge": { queryId: "query-c22-01", label: "每个轴都合规时，桥上同时存在的总载荷是多少？" },
  "c23-clean-air-sample": { queryId: "query-c23-01", label: "这份空气样本实际是从哪里采集的？" },
  "c24-turned-painting": { queryId: "query-c24-01", label: "画框封条完整，能证明展示面没有转向吗？" },
  "c25-silent-second-bell": { queryId: "query-c25-01", label: "按钮真的闭合了两次吗？" },
  "c26-short-map-pipeline": { queryId: "query-c26-01", label: "地图上的线长包含竖井里的折返段吗？" },
  "c27-stationary-moving-platform": { queryId: "query-c27-01", label: "平台回到原位时，货物还固定在上面吗？" },
  "c28-ninth-minute-temperature": { queryId: "query-c28-01", label: "探头读数会滞后于真实温度变化吗？" },
  "c29-role-stamp-signature": { queryId: "query-c29-01", label: "文件上的印记属于具体人物，还是岗位印章？" },
  "c30-shared-shift-id": { queryId: "query-c30-01", label: "同一个工号在两个时段属于同一个人吗？" },
  "c31-eighth-unchecked-guest": { queryId: "query-c31-01", label: "登记表统计的是独立住客，还是床位与合同？" },
  "c32-approved-unauthorized-door": { queryId: "query-c32-01", label: "这次开门权限来自个人授权，还是岗位组继承？" },
  "c33-early-late-arrival": { queryId: "query-c33-01", label: "门禁、录像和签到记录使用同一个时钟吗？" },
  "c34-tomorrow-seal": { queryId: "query-c34-01", label: "封条上的日期是印制日，还是封箱日？" },
  "c35-extra-glass-attendant": { queryId: "query-c35-01", label: "玻璃里多出的人影是直视人物，还是反射？" },
  "c36-no-one-left-terminal": { queryId: "query-c36-01", label: "计数、刷卡和调度记录描述的是同一个下车事件吗？" },
  "c37-zeroed-pressure-gauge": { queryId: "query-c37-01", label: "表针回零时，仪表零位仍可能偏移吗？" },
  "c38-no-missing-seventh-packet": { queryId: "query-c38-01", label: "序列号跳过，能证明数据包真的丢失吗？" },
  "c39-duplicated-heartbeat": { queryId: "query-c39-01", label: "两条心跳记录来自两次发送，还是一次回放？" },
  "c40-early-liquid-front": { queryId: "query-c40-01", label: "采样口先检测到液体，能证明储罐液面已经到达同一高度吗？" },
  "c41-hysteresis-overheat": { queryId: "query-c41-01", label: "第二次看到报警时，温度真的再次越过阈值了吗？" },
  "c42-same-weight-different-load": { queryId: "query-c42-01", label: "总重量相同，重心位置也一定相同吗？" },
  "c43-train-stop-reference": { queryId: "query-c43-01", label: "红线对应的是制动控制点，还是车轮停止点？" },
  "c44-hidden-overload-spike": { queryId: "query-c44-01", label: "平均值里没有尖峰，原始采样里也没有吗？" },
  "c45-double-location-second": { queryId: "query-c45-01", label: "两套定位记录使用同一个时间基准吗？" },
  "c46-pilot-pressure-valve": { queryId: "query-c46-01", label: "面板显示关闭时，阀芯的机械位置也一定关闭吗？" },
  "c47-offline-buffered-device": { queryId: "query-c47-01", label: "设备上线时间对应采集时间，还是补传到达时间？" },
  "c48-two-point-calibration": { queryId: "query-c48-01", label: "两个端点的校准记录都可靠吗？" },
  "c49-gimbal-turn-drone": { queryId: "query-c49-01", label: "画面转向来自无人机机身，还是云台？" },
  "c50-extra-warehouse-pallet": { queryId: "query-c50-01", label: "库存里的“一个”指托盘、批次，还是唯一货物？" },
  "c51-equivalent-resistance": { queryId: "query-c51-01", label: "测得的是单个电阻，还是并联后的等效阻值？" },
  "c52-shorter-river-night": { queryId: "query-c52-01", label: "夜间变化的是河道，还是测量水位的基准点？" },
  "c53-late-fiber-echo": { queryId: "query-c53-01", label: "回声时间同时包含光纤传播和设备缓冲吗？" },
  "c54-elevator-counterweight": { queryId: "query-c54-01", label: "轿厢没下降时，配重或检修模式改变了吗？" },
  "c55-merged-multi-alarm": { queryId: "query-c55-01", label: "多个告警源会被系统合并成一次声音吗？" },
  "c56-interpolated-temperature-map": { queryId: "query-c56-01", label: "温度图连续的区间都有真实采样点吗？" },
  "c57-lagging-wind-vane": { queryId: "query-c57-01", label: "风向标没动，能证明短时风向没有改变吗？" },
  "c58-same-volume-two-levels": { queryId: "query-c58-01", label: "两个容器的截面积沿高度相同吗？" },
  "c59-extra-ninth-floor": { queryId: "query-c59-01", label: "楼层估计是否把夹层或设备层重复计入？" },
  "c60-last-sample-before-stop": { queryId: "query-c60-01", label: "停止命令确实被控制器接收了吗？" },
};
