import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, relative, resolve, sep } from "node:path";
import {
  validateQuestionAliasPack,
  type CaseCatalogEntry,
  type CasePresentationPatch,
  type QuestionAliasPack,
} from "../packages/mystery-core/src/index.ts";
import { loadCaseFile, loadReleaseContent } from "./lib/release-content.ts";

const root = resolve(process.argv[2] ?? ".");
const profileId = process.argv[3] ?? process.env.TURTLE_SOUP_RELEASE_PROFILE ?? "v1.4-internal-rc";
const generatedDir = resolve(root, "apps/web/.generated");
const { profile, entries } = loadReleaseContent(root, profileId);
const patchPath = resolve(root, "content/zh/presentation", ["v1.4-internal-rc", "v1.5-internal-rc", "v1.6-internal-rc"].includes(profile.id) ? "v1.4/patches.json" : "v1.2/patches.json");
const presentationPatches: CasePresentationPatch[] = existsSync(patchPath)
  ? JSON.parse(readFileSync(patchPath, "utf8")) as CasePresentationPatch[]
  : [];
const patchByCase = ["v1.2-internal-rc", "v1.3-public-preview", "v1.4-internal-rc", "v1.5-internal-rc", "v1.6-internal-rc"].includes(profile.id) ? new Map(presentationPatches.map((patch) => [patch.caseId, patch])) : new Map();
const aliasVersion = profile.id === "v1.6-internal-rc" ? "v1.6" : "v1.5";
const aliasPath = resolve(root, `content/zh/question-aliases/${aliasVersion}/packs.json`);
const aliasPacks: QuestionAliasPack[] = ["v1.5-internal-rc", "v1.6-internal-rc"].includes(profile.id) && existsSync(aliasPath)
  ? JSON.parse(readFileSync(aliasPath, "utf8")) as QuestionAliasPack[]
  : [];
const aliasByCase = new Map(aliasPacks.map((pack) => [pack.caseId, pack]));
for (const entry of entries) {
  const pack = aliasByCase.get(entry.id);
  if (!pack) continue;
  const validation = validateQuestionAliasPack(loadCaseFile(entry), pack);
  if (!validation.valid) throw new Error(`${entry.id}: invalid QuestionAliasPack: ${validation.failures.join("; ")}`);
}
for (const pack of aliasPacks) if (!entries.some((entry) => entry.id === pack.caseId)) throw new Error(`Alias pack references unpublished case ${pack.caseId}`);
const publicCatalog: CaseCatalogEntry[] = entries.map((entry) => {
  const caseFile = loadCaseFile(entry);
  const patch = patchByCase.get(entry.id);
  const zh = caseFile.localization?.["zh-CN"] ?? {};
  const authored = entry.public ?? {};
  const code = entry.id.match(/^(c\d+)/)?.[1];
  const rasterScene = profile.id === "v1.1-internal-rc" && code ? `/assets/cases/${code}/scene-desktop.webp` : undefined;
  const rasterSceneMobile = profile.id === "v1.1-internal-rc" && code ? `/assets/cases/${code}/scene-mobile.webp` : undefined;
  return {
    id: entry.id,
    title: String(patch?.title ?? authored.title ?? zh[caseFile.surface?.titleKey ?? caseFile.metadata?.titleKey ?? ""] ?? entry.id),
    surface: String(patch?.surface ?? authored.surface ?? zh[caseFile.surface?.textKey ?? ""] ?? "一件等待证明的异常事件。"),
    difficulty: String(authored.difficulty ?? caseFile.metadata?.difficulty ?? "unknown"),
    targetMinutes: caseFile.metadata?.targetMinutes ?? { min: 5, max: 20 },
    contentTags: (authored.contentTags ?? caseFile.metadata?.contentTags ?? []) as string[],
    layoutId: String(authored.layoutId ?? caseFile.presentation?.layoutId ?? "cold-room"),
    sceneAsset: String(patch?.sceneAsset ?? rasterScene ?? authored.sceneAsset ?? caseFile.presentation?.sceneAsset ?? "/scene-cold-room.svg"),
    sceneAssetMobile: String(patch?.sceneAssetMobile ?? patch?.sceneAsset ?? rasterSceneMobile ?? authored.sceneAssetMobile ?? caseFile.presentation?.sceneAssetMobile ?? authored.sceneAsset ?? caseFile.presentation?.sceneAsset ?? "/scene-cold-room.svg"),
    accent: String(authored.accent ?? caseFile.presentation?.accent ?? "#b8cf79"),
    seasonId: entry.seasonId,
    seasonTitle: entry.seasonTitle,
    status: entry.status as CaseCatalogEntry["status"],
    mechanicTags: (authored.contentTags ?? caseFile.metadata?.contentTags ?? []) as string[],
    replayChallenges: patch?.replayChallenges ?? caseFile.replayChallenges ?? [],
  };
});
const identities = Object.fromEntries(entries.map((entry) => [entry.id, { caseVersion: entry.contentVersion, contentHash: entry.canonicalHash }]));
const publicSource = `// Generated by tools/generate-content-registry.ts for ${profile.id}. Do not edit.\nimport type { CaseCatalogEntry, SaveIdentity } from "@turtle-soup/mystery-core";\nexport const RELEASE_PROFILE = ${JSON.stringify({ id: profile.id, title: profile.title, status: profile.status, publishable: profile.publishable ?? false, humanEvaluation: profile.humanEvaluation ?? "pending" }, null, 2)} as const;\nexport const CASE_CATALOG = ${JSON.stringify(publicCatalog, null, 2)} satisfies CaseCatalogEntry[];\nexport const CASE_SAVE_IDENTITIES: Readonly<Record<string, SaveIdentity>> = ${JSON.stringify(identities, null, 2)};\n`;
const loaderLines = entries.map((entry) => {
  const fromGenerated = relative(generatedDir, entry.casePath).split(sep).join("/");
  const specifier = fromGenerated.startsWith(".") ? fromGenerated : `./${fromGenerated}`;
  return `  ${JSON.stringify(entry.id)}: async () => (await import(${JSON.stringify(specifier)})).default as CaseFile,`;
});
const workerSource = `// Generated by tools/generate-content-registry.ts for ${profile.id}. Worker-only truth registry.\nimport type { CaseFile } from "@turtle-soup/mystery-core";\nconst loaders: Record<string, () => Promise<CaseFile>> = {\n${loaderLines.join("\n")}\n};\nexport async function loadCaseFile(caseId: string): Promise<CaseFile> {\n  const loader = loaders[caseId];\n  if (!loader) throw new Error(\`Unknown case id: \${caseId}\`);\n  const caseFile = await loader();\n  if (caseFile.id !== caseId) throw new Error(\`Case identity mismatch for \${caseId}\`);\n  return caseFile;\n}\n`;
const patchSource = `// Generated by tools/generate-content-registry.ts. Worker-only public-copy patches.\nimport type { CasePresentationPatch } from "@turtle-soup/mystery-core";\nexport const PRESENTATION_PATCHES: Readonly<Record<string, CasePresentationPatch>> = ${JSON.stringify(Object.fromEntries(entries.map((entry) => [entry.id, patchByCase.get(entry.id)]).filter(([, patch]) => Boolean(patch))), null, 2)};\n`;
const aliasSource = `// Generated by tools/generate-content-registry.ts. Worker-only deterministic language aliases.\nimport type { QuestionAliasPack } from "@turtle-soup/mystery-core";\nexport const QUESTION_ALIAS_PACKS: Readonly<Record<string, QuestionAliasPack>> = ${JSON.stringify(Object.fromEntries(aliasPacks.map((pack) => [pack.caseId, pack])), null, 2)};\n`;
mkdirSync(generatedDir, { recursive: true });
writeFileSync(resolve(generatedDir, "public-catalog.ts"), publicSource, "utf8");
writeFileSync(resolve(generatedDir, "worker-case-registry.ts"), workerSource, "utf8");
writeFileSync(resolve(generatedDir, "presentation-patch-registry.ts"), patchSource, "utf8");
writeFileSync(resolve(generatedDir, "question-alias-registry.ts"), aliasSource, "utf8");
console.log(JSON.stringify({ profile: profile.id, cases: entries.length, generatedDir }, null, 2));
