import { createHash } from "node:crypto";
import { cpSync, existsSync, mkdirSync, readdirSync, rmSync, statSync, readFileSync, writeFileSync } from "node:fs";
import { relative, resolve, sep } from "node:path";

const root = resolve(process.argv[2] ?? ".");
const source = resolve(root, "apps/web/out");
const dist = resolve(root, "dist/v1.9-internal-rc-web-pwa");
const archive = resolve(root, "dist/turtle-soup-v1.9-internal-rc-web-pwa.zip");
if (!existsSync(source)) throw new Error("Run the v1.9 build first");
rmSync(dist, { recursive: true, force: true }); mkdirSync(dist, { recursive: true }); cpSync(source, dist, { recursive: true });
writeFileSync(resolve(dist, "INTERNAL-RC.txt"), "TURTLE SOUP v1.9 AI LANGUAGE BRIDGE & FRONTEND RECONSTRUCTION INTERNAL RC\r\n\r\n60 deterministic cases. Founder exploratory sessions: 1. Formal Fun Gate participants: 0. Human evaluation: PENDING. Automation does not prove fun, aesthetics, comprehension, retention or market fit.\r\n", "utf8");
function files(dir: string): string[] { return readdirSync(dir).flatMap((name) => { const path = resolve(dir, name); return statSync(path).isDirectory() ? files(path) : [path]; }); }
const crcTable = Array.from({ length: 256 }, (_, value) => { let crc = value; for (let bit = 0; bit < 8; bit += 1) crc = (crc & 1) ? 0xedb88320 ^ (crc >>> 1) : crc >>> 1; return crc >>> 0; });
function crc32(data: Buffer) { let crc = 0xffffffff; for (const value of data) crc = crcTable[(crc ^ value) & 0xff] ^ (crc >>> 8); return (crc ^ 0xffffffff) >>> 0; }
function deterministicZip(paths: string[]) { const locals: Buffer[] = [], central: Buffer[] = []; let offset = 0; for (const path of paths) { const name = Buffer.from(relative(dist, path).split(sep).join("/"), "utf8"), data = readFileSync(path), crc = crc32(data); const local = Buffer.alloc(30); local.writeUInt32LE(0x04034b50, 0); local.writeUInt16LE(20, 4); local.writeUInt16LE(0x0800, 6); local.writeUInt16LE(0x21, 12); local.writeUInt32LE(crc, 14); local.writeUInt32LE(data.length, 18); local.writeUInt32LE(data.length, 22); local.writeUInt16LE(name.length, 26); locals.push(local, name, data); const entry = Buffer.alloc(46); entry.writeUInt32LE(0x02014b50, 0); entry.writeUInt16LE(20, 4); entry.writeUInt16LE(20, 6); entry.writeUInt16LE(0x0800, 8); entry.writeUInt16LE(0x21, 14); entry.writeUInt32LE(crc, 16); entry.writeUInt32LE(data.length, 20); entry.writeUInt32LE(data.length, 24); entry.writeUInt16LE(name.length, 28); entry.writeUInt32LE(offset, 42); central.push(entry, name); offset += local.length + name.length + data.length; } const centralSize = central.reduce((sum, item) => sum + item.length, 0), end = Buffer.alloc(22); end.writeUInt32LE(0x06054b50, 0); end.writeUInt16LE(paths.length, 8); end.writeUInt16LE(paths.length, 10); end.writeUInt32LE(centralSize, 12); end.writeUInt32LE(offset, 16); return Buffer.concat([...locals, ...central, end]); }
const contentFiles = files(dist).sort((a, b) => relative(dist, a).localeCompare(relative(dist, b))), zip = deterministicZip(contentFiles); writeFileSync(archive, zip);
const preserved = [{ version: "v1.8", path: "dist/turtle-soup-v1.8-internal-rc-web-pwa.zip", expected: "43b6dff6b70abec6a74788bb28fba6f7301eb91dd892818584c82f48fc88d30d" }].map((item) => ({ ...item, actual: existsSync(resolve(root, item.path)) ? createHash("sha256").update(readFileSync(resolve(root, item.path))).digest("hex") : null, unchanged: existsSync(resolve(root, item.path)) && createHash("sha256").update(readFileSync(resolve(root, item.path))).digest("hex") === item.expected }));
const report = { reportVersion: "1.9", releaseProfile: "v1.9-internal-rc", generatedAt: new Date().toISOString(), status: "internal-rc / human-evaluation-pending", humanParticipants: 0, founderExploratorySessions: 1, deterministicArchive: { method: "ZIP store", timestamp: "1980-01-01" }, artifact: { directory: "dist/v1.9-internal-rc-web-pwa", bytes: contentFiles.reduce((sum, path) => sum + statSync(path).size, 0), files: contentFiles.length, archive: { path: "dist/turtle-soup-v1.9-internal-rc-web-pwa.zip", bytes: zip.length, sha256: createHash("sha256").update(zip).digest("hex") } }, preservedArtifacts: preserved, passed: zip.length <= 7_000_000 && preserved.every((item) => item.unchanged) };
writeFileSync(resolve(root, "docs/v1.9-release-artifacts.json"), `${JSON.stringify(report, null, 2)}\n`, "utf8"); console.log(JSON.stringify({ artifact: report.artifact, preserved, passed: report.passed }, null, 2)); if (!report.passed) process.exitCode = 1;
