import AxeBuilder from "@axe-core/playwright";
import { createServer } from "node:http";
import { mkdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { extname, resolve } from "node:path";
import { chromium, firefox, webkit, type BrowserType } from "playwright";
import { loadReleaseContent } from "./lib/release-content.ts";
const root = resolve(process.argv[2] ?? "."); const outDir = resolve(root, "apps/web/out"); const reportPath = resolve(root, "docs/v1.1-browser-matrix.json"); const outputDir = resolve(root, "output/playwright/v11"); const { entries } = loadReleaseContent(root, "v1.1-internal-rc"); const mime: Record<string, string> = { ".html": "text/html; charset=utf-8", ".js": "text/javascript; charset=utf-8", ".css": "text/css; charset=utf-8", ".json": "application/json", ".webmanifest": "application/manifest+json", ".webp": "image/webp", ".svg": "image/svg+xml", ".png": "image/png" };
function pathFor(url: string) { const pathname = decodeURIComponent(new URL(url, "http://localhost").pathname); const candidate = resolve(outDir, `.${pathname}`); if (!candidate.startsWith(outDir)) return undefined; try { return statSync(candidate).isDirectory() ? resolve(candidate, "index.html") : candidate; } catch { return pathname.endsWith("/") ? resolve(candidate, "index.html") : candidate; } }
const server = createServer((request, response) => { const path = pathFor(request.url ?? "/"); if (!path) { response.writeHead(403); response.end(); return; } try { const body = readFileSync(path); response.writeHead(200, { "content-type": mime[extname(path)] ?? "application/octet-stream", "cache-control": "no-cache" }); response.end(body); } catch { response.writeHead(404); response.end("Not found"); } }); await new Promise<void>((done) => server.listen(4178, "127.0.0.1", done)); const base = "http://127.0.0.1:4178"; mkdirSync(outputDir, { recursive: true });
async function auditBrowser(name: string, type: BrowserType) { const browser = await type.launch(); const context = await browser.newContext({ viewport: { width: 1440, height: 900 }, reducedMotion: "reduce" }); const page = await context.newPage(); const errors: string[] = []; page.on("console", (message) => { if (message.type() === "error") errors.push(message.text()); }); await page.goto(base, { waitUntil: "networkidle" }); const links = await page.locator('a[href*="/case/"]').count(); const seasons = await page.locator("section h2").count(); const axe = await new AxeBuilder({ page }).analyze(); const serious = axe.violations.filter((item) => item.impact === "serious" || item.impact === "critical").map((item) => item.id); const cases = []; for (const entry of entries) { const response = await page.goto(`${base}/case/${entry.id}/`, { waitUntil: "networkidle" }); const input = page.locator('input[name="investigation-question"]'); await input.waitFor({ state: "attached" }); const boardCount = await page.locator('[aria-label$="推理板"]').count(); const overflow = await page.evaluate(() => Math.max(0, document.documentElement.scrollWidth - document.documentElement.clientWidth)); cases.push({ id: entry.id, status: response?.status(), boardCount, overflow, passed: response?.ok() && boardCount >= 0 && overflow <= 1 }); } await page.goto(`${base}/case/not-a-real-case/`, { waitUntil: "domcontentloaded" }); const unknown = page.url().includes("not-a-real-case") === false || (await page.getByText("档案无法打开").count()) === 0; if (name === "chromium") await page.screenshot({ path: resolve(outputDir, "home-desktop.png"), fullPage: true }); await browser.close(); return { name, links, seasons, seriousAxe: serious, consoleErrors: errors, unknownFailedClosed: unknown, cases, passed: links === 36 && seasons >= 3 && serious.length === 0 && unknown && cases.every((item) => item.passed) }; }
async function mobileAudit() { const browser = await chromium.launch(); const context = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true }); const page = await context.newPage(); const results = []; for (const entry of entries.filter((item) => item.seasonId === "season-3")) { await page.goto(`${base}/case/${entry.id}/`, { waitUntil: "networkidle" }); const nav = page.getByRole("navigation", { name: "调查区域" }); await nav.getByRole("button").last().click(); const boardVisible = await page.locator('[aria-label$="推理板"]').first().isVisible(); const overflow = await page.evaluate(() => Math.max(0, document.documentElement.scrollWidth - document.documentElement.clientWidth)); results.push({ id: entry.id, boardVisible, overflow, passed: boardVisible && overflow <= 1 }); } await page.goto(base, { waitUntil: "networkidle" }); await page.reload({ waitUntil: "networkidle" }); await context.setOffline(true); let offlineReady = true; try { await page.reload({ waitUntil: "domcontentloaded", timeout: 15000 }); offlineReady = await page.locator("main").count() === 1; } catch { offlineReady = false; } await context.setOffline(false); await page.screenshot({ path: resolve(outputDir, "home-mobile.png"), fullPage: true }); await browser.close(); return { viewport: "390x844", cases: results, offlineReady, passed: offlineReady && results.every((item) => item.passed) }; }
try { const desktop = []; for (const [name, type] of [["chromium", chromium], ["firefox", firefox], ["webkit", webkit]] as const) desktop.push(await auditBrowser(name, type)); const mobile = await mobileAudit(); const report = { reportVersion: "1.1", generatedAt: new Date().toISOString(), releaseProfile: "v1.1-internal-rc", humanParticipants: 0, cases: entries.length, desktop, mobile, screenshots: 2, passed: desktop.every((item) => item.passed) && mobile.passed }; writeFileSync(reportPath, JSON.stringify(report, null, 2), "utf8"); console.log(JSON.stringify({ reportPath, passed: report.passed, desktop: desktop.map((item) => ({ name: item.name, routes: item.cases.length, passed: item.passed })), mobile: { routes: mobile.cases.length, passed: mobile.passed } }, null, 2)); if (!report.passed) process.exitCode = 1; } finally { await new Promise<void>((done) => server.close(() => done())); }
