import AxeBuilder from "@axe-core/playwright";
import { createServer } from "node:http";
import { existsSync, mkdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { extname, resolve } from "node:path";
import { chromium, firefox, webkit, type BrowserType } from "playwright";
import { loadReleaseContent } from "./lib/release-content.ts";

const root = resolve(process.argv[2] ?? "."); const outDir = resolve(root, "apps/web/out"); const outputDir = resolve(root, "output/playwright/v12"); const reportPath = resolve(root, "docs/v1.2-browser-matrix.json"); const entries = loadReleaseContent(root, "v1.2-internal-rc").entries;
const mime: Record<string, string> = { ".html": "text/html; charset=utf-8", ".js": "text/javascript; charset=utf-8", ".css": "text/css; charset=utf-8", ".json": "application/json", ".webmanifest": "application/manifest+json", ".webp": "image/webp", ".svg": "image/svg+xml", ".png": "image/png", ".ico": "image/svg+xml" };
function pathFor(url: string) { const pathname = decodeURIComponent(new URL(url, "http://localhost").pathname); const candidate = resolve(outDir, `.${pathname}`); if (!candidate.startsWith(outDir)) return undefined; try { if (statSync(candidate).isDirectory()) { const index = resolve(candidate, "index.html"); return existsSync(index) ? index : undefined; } return candidate; } catch { return undefined; } }
const server = createServer((request, response) => { const path = pathFor(request.url ?? "/"); if (!path) { try { const body = readFileSync(resolve(outDir, "404.html")); response.writeHead(404, { "content-type": "text/html; charset=utf-8" }); response.end(body); } catch { response.writeHead(404); response.end("Not found"); } return; } try { const body = readFileSync(path); response.writeHead(200, { "content-type": mime[extname(path)] ?? "application/octet-stream", "cache-control": "no-cache" }); response.end(body); } catch { response.writeHead(404); response.end("Not found"); } });
await new Promise<void>((done, reject) => { server.once("error", reject); server.listen(0, "127.0.0.1", done); }); const address = server.address(); if (!address || typeof address === "string") throw new Error("browser_audit_server_failed"); const base = `http://127.0.0.1:${address.port}`; mkdirSync(outputDir, { recursive: true });
async function desktopAudit(name: string, type: BrowserType) { const browser = await type.launch(); const context = await browser.newContext({ viewport: { width: 1440, height: 900 }, reducedMotion: "reduce" }); const page = await context.newPage(); const errors: string[] = []; page.on("console", (message) => { if (message.type() === "error") errors.push(message.text()); }); const homeResponse = await page.goto(base, { waitUntil: "networkidle" }); const links = await page.locator('a[href*="/case/"]').count(); const seasons = await page.locator('summary[aria-controls^="cases-"]').count(); const axe = await new AxeBuilder({ page }).analyze(); const seriousAxe = axe.violations.filter((item) => item.impact === "serious" || item.impact === "critical").map((item) => item.id); if (name === "chromium") await page.screenshot({ path: resolve(outputDir, "home-desktop.png"), fullPage: true }); const cases = []; for (const entry of entries) { const response = await page.goto(`${base}/case/${entry.id}/`, { waitUntil: "networkidle" }); const input = page.locator('input[name="investigation-question"]'); await input.waitFor({ state: "attached" }); const boardCount = await page.locator('[aria-label$="推理板"]').count(); const selector = await page.locator('[aria-label="选择推理板"]').count(); const overflow = await page.evaluate(() => Math.max(0, document.documentElement.scrollWidth - document.documentElement.clientWidth)); cases.push({ id: entry.id, status: response?.status(), boardCount, selector, overflow, passed: response?.status() === 200 && overflow <= 1 }); }
  const knownErrors = [...errors]; errors.length = 0; const unknownResponse = await page.goto(`${base}/case/not-a-real-case/`, { waitUntil: "domcontentloaded" }); const unknownStatus = unknownResponse?.status(); const unknownText = await page.getByText("档案无法打开").count(); if (name === "chromium") await page.screenshot({ path: resolve(outputDir, "unknown-case-404.png"), fullPage: true }); await browser.close(); return { name, homeStatus: homeResponse?.status(), links, seasons, seriousAxe, consoleErrors: knownErrors, unknownStatus, unknownText, cases, passed: homeResponse?.status() === 200 && links === entries.length && seasons >= 3 && seriousAxe.length === 0 && knownErrors.length === 0 && unknownStatus === 404 && unknownText > 0 && cases.every((item) => item.passed) }; }
async function mobileAudit() { const browser = await chromium.launch(); const context = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, reducedMotion: "reduce" }); const page = await context.newPage(); const results = []; for (const id of ["c01-cold-room-knock", "c25-silent-second-bell", "c36-no-one-left-terminal"]) { await page.goto(`${base}/case/${id}/`, { waitUntil: "networkidle" }); const overflow = await page.evaluate(() => Math.max(0, document.documentElement.scrollWidth - document.documentElement.clientWidth)); const nav = await page.getByRole("navigation", { name: "调查区域" }).count(); results.push({ id, nav, overflow, passed: nav === 1 && overflow <= 1 }); } await page.goto(base, { waitUntil: "networkidle" }); const mobileSections = await page.locator('summary[aria-controls^="cases-"]').count(); await page.screenshot({ path: resolve(outputDir, "home-mobile.png"), fullPage: true }); await browser.close(); return { viewport: "390x844", mobileSections, cases: results, passed: mobileSections >= 3 && results.every((item) => item.passed) }; }
try { const desktop = []; for (const [name, type] of [["chromium", chromium], ["firefox", firefox], ["webkit", webkit]] as const) desktop.push(await desktopAudit(name, type)); const mobile = await mobileAudit(); const report = { reportVersion: "1.2", generatedAt: new Date().toISOString(), releaseProfile: "v1.2-internal-rc", humanParticipants: 0, cases: entries.length, desktop, mobile, screenshots: ["home-desktop.png", "home-mobile.png", "unknown-case-404.png"], passed: desktop.every((item) => item.passed) && mobile.passed }; writeFileSync(reportPath, JSON.stringify(report, null, 2), "utf8"); console.log(JSON.stringify({ reportPath, passed: report.passed, desktop: desktop.map((item) => ({ name: item.name, passed: item.passed, consoleErrors: item.consoleErrors.length })), mobile: mobile.passed }, null, 2)); if (!report.passed) process.exitCode = 1; } finally { await new Promise<void>((done) => server.close(() => done())); }
