import AxeBuilder from "@axe-core/playwright";
import { createServer } from "node:http";
import { existsSync, mkdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { extname, resolve } from "node:path";
import { chromium, firefox, webkit } from "playwright";
import { loadReleaseContent } from "./lib/release-content.ts";

const root = resolve(process.argv[2] ?? ".");
const outDir = resolve(root, "apps/web/out");
const outputDir = resolve(root, "output/playwright/v13");
mkdirSync(outputDir, { recursive: true });
const entries = loadReleaseContent(root, "v1.3-public-preview").entries;
const mime: Record<string, string> = { ".html": "text/html; charset=utf-8", ".js": "text/javascript; charset=utf-8", ".css": "text/css; charset=utf-8", ".json": "application/json", ".webmanifest": "application/manifest+json", ".webp": "image/webp", ".svg": "image/svg+xml", ".png": "image/png", ".ico": "image/x-icon" };
function staticPath(url: string) { const pathname = decodeURIComponent(new URL(url, "http://localhost").pathname); const candidate = resolve(outDir, `.${pathname}`); if (!candidate.toLowerCase().startsWith(outDir.toLowerCase())) return undefined; try { if (statSync(candidate).isDirectory()) { const index = resolve(candidate, "index.html"); return existsSync(index) ? index : undefined; } return candidate; } catch { return undefined; } }
const server = createServer((request, response) => { const path = staticPath(request.url ?? "/"); if (!path) { const notFound = resolve(outDir, "404.html"); response.writeHead(404, { "content-type": "text/html; charset=utf-8" }); response.end(existsSync(notFound) ? readFileSync(notFound) : "Not found"); return; } response.writeHead(200, { "content-type": mime[extname(path).toLowerCase()] ?? "application/octet-stream", "cache-control": "no-cache" }); response.end(readFileSync(path)); });
await new Promise<void>((done, reject) => { server.once("error", reject); server.listen(0, "127.0.0.1", done); });
const address = server.address(); if (!address || typeof address === "string") throw new Error("browser_audit_server_failed"); const base = `http://127.0.0.1:${address.port}`;
const representativeIds = ["c01-cold-room-knock", "c04-unpostable-reply", "c06-nonexistent-ticket", "c08-unclaimed-recording", "c10-single-ring", "c12-zero-floor-elevator", "c13-second-waterline", "c16-closed-door-handoff", "c19-fog-after-window", "c21-missing-seven-minutes", "c23-clean-air-sample", "c24-turned-painting", "c25-silent-second-bell", "c28-ninth-minute-temperature", "c31-eighth-unchecked-guest", "c33-early-late-arrival", "c35-extra-glass-attendant", "c36-no-one-left-terminal", "c37-zeroed-pressure-gauge", "c42-same-weight-different-load", "c48-two-point-calibration", "c54-elevator-counterweight", "c57-lagging-wind-vane", "c60-last-sample-before-stop"];
async function visit(page: import("playwright").Page, path: string) { const response = await page.goto(`${base}${path}`, { waitUntil: "domcontentloaded", timeout: 10000 }); await page.waitForFunction(() => !document.body.textContent?.includes("正在校验案件档案"), { timeout: 10000 }).catch(() => undefined); return response; }
async function runBrowser(name: string, type: typeof chromium) { const browser = await type.launch(); const context = await browser.newContext({ viewport: { width: 1440, height: 900 }, reducedMotion: "reduce", serviceWorkers: "block" }); const page = await context.newPage(); const errors: string[] = []; page.on("console", (message) => { if (message.type() === "error" && !message.text().includes("404")) errors.push(message.text()); }); const home = await visit(page, "/"); const routes = []; for (const entry of entries) { const response = await visit(page, `/case/${entry.id}/`); const overflow = await page.evaluate(() => Math.max(0, document.documentElement.scrollWidth - document.documentElement.clientWidth)); const title = await page.locator("main h1:visible").first().textContent().catch(() => ""); routes.push({ caseId: entry.id, status: response?.status(), title, overflow, passed: response?.status() === 200 && Boolean(title) && overflow <= 1 }); } const unknown = await visit(page, "/case/not-a-real-case/"); const unknownStatus = unknown?.status(); await visit(page, "/"); await page.screenshot({ path: resolve(outputDir, `${name}-home-desktop.png`), fullPage: true }); await context.close(); await browser.close(); return { browser: name, homeStatus: home?.status(), unknownStatus, consoleErrors: errors, routes, passed: home?.status() === 200 && unknownStatus === 404 && errors.length === 0 && routes.every((item) => item.passed) }; }
async function runRepresentatives() { const browser = await chromium.launch(); const desktop = await browser.newContext({ viewport: { width: 1440, height: 900 }, reducedMotion: "reduce", serviceWorkers: "block" }); const mobile = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, reducedMotion: "reduce", serviceWorkers: "block" }); const traces = []; for (const caseId of representativeIds) { const page = await desktop.newPage(); await visit(page, `/case/${caseId}/`); const input = page.locator('input[name="investigation-question"]'); if (await input.count()) { await input.fill("请确认这条记录是否成立"); await input.press("Enter").catch(() => undefined); } const overflow = await page.evaluate(() => Math.max(0, document.documentElement.scrollWidth - document.documentElement.clientWidth)); await page.screenshot({ path: resolve(outputDir, `${caseId}-desktop.png`), fullPage: true }); traces.push({ caseId, queryAttempted: await input.count() > 0, boardCount: await page.locator('[aria-label$="推理板"]').count(), overflow, passed: await input.count() > 0 && overflow <= 1 }); await page.close(); } const mobilePage = await mobile.newPage(); await visit(mobilePage, "/case/c60-last-sample-before-stop/"); const mobileOverflow = await mobilePage.evaluate(() => Math.max(0, document.documentElement.scrollWidth - document.documentElement.clientWidth)); await mobilePage.screenshot({ path: resolve(outputDir, "c60-mobile.png"), fullPage: true }); const axe = await new AxeBuilder({ page: mobilePage }).analyze(); const blockers = axe.violations.filter((item) => item.impact === "serious" || item.impact === "critical").length; await mobilePage.close(); await desktop.close(); await mobile.close(); return { representativeIds, traces, mobileOverflow, axeSeriousCritical: blockers, passed: traces.every((item) => item.passed) && mobileOverflow <= 1 && blockers === 0 }; }
try { const browsers = []; for (const [name, type] of [["chromium", chromium], ["firefox", firefox], ["webkit", webkit]] as const) browsers.push(await runBrowser(name, type)); const representatives = await runRepresentatives(); const report = { reportVersion: "1.3", generatedAt: new Date().toISOString(), releaseProfile: "v1.3-public-preview", humanParticipants: 0, engines: ["chromium", "firefox", "webkit"], viewports: ["1440x900", "390x844"], caseCount: entries.length, representativeCount: representativeIds.length, browsers, representatives, screenshots: ["chromium-home-desktop.png", "firefox-home-desktop.png", "webkit-home-desktop.png", "c60-mobile.png", ...representativeIds.map((id) => `${id}-desktop.png`)], passed: browsers.every((item) => item.passed) && representatives.passed, qualification: "Automation validates route, rendering, responsive and accessibility lower bounds. Human comprehension, fun, pacing and market fit remain pending." }; writeFileSync(resolve(root, "docs/v1.3-browser-matrix.json"), JSON.stringify(report, null, 2), "utf8"); console.log(JSON.stringify({ passed: report.passed, routeCount: entries.length * 3, representativeCount: representativeIds.length }, null, 2)); if (!report.passed) process.exitCode = 1; } finally { await new Promise<void>((done) => server.close(() => done())); }
