import { createServer } from "node:http";
import { existsSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { extname, resolve } from "node:path";
import { chromium } from "playwright";
import { loadCaseFile, loadReleaseContent } from "./lib/release-content.ts";
import { createCanonicalSave } from "./lib/canonical-save.ts";

const root = resolve(process.argv[2] ?? "."); const outDir = resolve(root, "apps/web/out"); const release = loadReleaseContent(root, "v1.3-public-preview"); const byId = new Map(release.entries.map((entry) => [entry.id, loadCaseFile(entry)]));
const ids = ["c01-cold-room-knock", "c04-unpostable-reply", "c06-nonexistent-ticket", "c08-unclaimed-recording", "c10-single-ring", "c12-zero-floor-elevator", "c13-second-waterline", "c16-closed-door-handoff", "c19-fog-after-window", "c21-missing-seven-minutes", "c23-clean-air-sample", "c24-turned-painting", "c25-silent-second-bell", "c28-ninth-minute-temperature", "c31-eighth-unchecked-guest", "c33-early-late-arrival", "c35-extra-glass-attendant", "c36-no-one-left-terminal", "c37-zeroed-pressure-gauge", "c42-same-weight-different-load", "c48-two-point-calibration", "c54-elevator-counterweight", "c57-lagging-wind-vane", "c60-last-sample-before-stop"];
const mime: Record<string, string> = { ".html": "text/html; charset=utf-8", ".js": "text/javascript; charset=utf-8", ".css": "text/css", ".json": "application/json", ".webmanifest": "application/manifest+json", ".svg": "image/svg+xml", ".webp": "image/webp", ".png": "image/png", ".ico": "image/x-icon" };
function pathFor(url: string) { const pathname = decodeURIComponent(new URL(url, "http://localhost").pathname); const candidate = resolve(outDir, `.${pathname}`); if (!candidate.toLowerCase().startsWith(outDir.toLowerCase())) return undefined; try { if (statSync(candidate).isDirectory()) { const index = resolve(candidate, "index.html"); return existsSync(index) ? index : undefined; } return candidate; } catch { return undefined; } }
const server = createServer((request, response) => { const path = pathFor(request.url ?? "/"); if (!path) { response.writeHead(404); response.end("Not found"); return; } response.writeHead(200, { "content-type": mime[extname(path)] ?? "application/octet-stream" }); response.end(readFileSync(path)); }); await new Promise<void>((done) => server.listen(0, "127.0.0.1", done)); const address = server.address(); if (!address || typeof address === "string") throw new Error("server failed"); const base = `http://127.0.0.1:${address.port}`;
async function inject(page: import("playwright").Page, key: string, save: unknown) { await page.evaluate(async ({ key, save }) => { const database = await new Promise<IDBDatabase>((done, reject) => { const request = indexedDB.open("turtle-soup", 1); request.onupgradeneeded = () => { if (!request.result.objectStoreNames.contains("case-saves")) request.result.createObjectStore("case-saves"); }; request.onerror = () => reject(request.error); request.onsuccess = () => done(request.result); }); await new Promise<void>((done, reject) => { const transaction = database.transaction("case-saves", "readwrite"); transaction.objectStore("case-saves").put(save, key); transaction.oncomplete = () => done(); transaction.onerror = () => reject(transaction.error); }); database.close(); }, { key, save }); }
const browser = await chromium.launch(); const context = await browser.newContext({ viewport: { width: 1440, height: 900 }, serviceWorkers: "block" }); const traces = [];
try { for (const id of ids) { const caseFile = byId.get(id); if (!caseFile) throw new Error(`${id} missing`); const page = await context.newPage(); const errors: string[] = []; page.on("console", (message) => { if (message.type() === "error") errors.push(message.text()); }); await page.goto(`${base}/case/${id}/`, { waitUntil: "domcontentloaded" }); const input = page.locator('input[name="investigation-question"]'); await input.waitFor({ timeout: 10000 }); let questions = 0; for (const query of caseFile.questionSemantics.slice(0, 3)) { await input.fill(query.examplePhrases?.[0] ?? String(query.id)); await input.press("Enter"); await page.waitForTimeout(40); const chooser = page.getByRole("group", { name: "确认问题解释" }); if (await chooser.count()) await chooser.getByRole("button").first().click(); questions += 1; } const beforeSaveTranscript = await page.locator('[class*="transcript"] article, [class*="exchange"]').count(); const save = createCanonicalSave(caseFile); await inject(page, id, save); await page.reload({ waitUntil: "domcontentloaded" }); await input.waitFor({ timeout: 10000 }); const closed = await page.getByText(/CASE CLOSED|CLOSED|案件已结案/).count() > 0; const replay = await page.getByText(/证明：|证据：|证明回放/).count() > 0; const challenges = await page.getByText(/限定问题|最小证据|关闭快捷/).count(); await page.reload({ waitUntil: "domcontentloaded" }); await input.waitFor({ timeout: 10000 }); const restored = await page.getByText(/CASE CLOSED|CLOSED|案件已结案/).count() > 0; const passed = questions === 3 && beforeSaveTranscript >= 3 && closed && replay && restored && errors.length === 0; traces.push({ caseId: id, questions, transcriptEntries: beforeSaveTranscript, canonicalSaveCommands: save.commands.length, closed, replay, challengeLabels: challenges, refreshRestored: restored, consoleErrors: errors, passed }); await page.close(); } } finally { await context.close(); await browser.close(); await new Promise<void>((done) => server.close(() => done())); }
const report = { reportVersion: "1.3", generatedAt: new Date().toISOString(), releaseProfile: "v1.3-public-preview", browser: "chromium", viewport: "1440x900", humanParticipants: 0, representativeCases: ids.length, traces, passed: traces.every((item) => item.passed), qualification: "Canonical browser saves exercise the same public command protocol and Worker replay. Human understanding, pacing and fun remain pending." }; writeFileSync(resolve(root, "docs/v1.3-full-flow-traces.json"), JSON.stringify(report, null, 2), "utf8"); console.log(JSON.stringify({ representativeCases: ids.length, passed: report.passed }, null, 2)); if (!report.passed) process.exitCode = 1;
