import { createHash } from "node:crypto";
import { existsSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { extname, resolve } from "node:path";
import { createQuestionRoutingOffer, createRuntimeState, projectPlayerState } from "../packages/mystery-core/src/index.ts";
import { buildQuestionRoutingRequestBody } from "../apps/web/lib/question-routing-ai.ts";
import { loadCaseFile, loadReleaseContent } from "./lib/release-content.ts";

const root = resolve(process.argv[2] ?? "."), out = resolve(root, "apps/web/out");
const release = loadReleaseContent(root, "v1.9-internal-rc");
const forbidden = ["solutionCertificate", "canonicalHypothesisId", "requiredFactIds", "alternativeHypothesisIds", "fact-", "query-", "hypothesis-", "apiKey", "authorization", "Bearer "];
const projectionChecks = release.entries.map((entry) => { const caseFile = loadCaseFile(entry), state = createRuntimeState(caseFile), projection = JSON.stringify(projectPlayerState(caseFile, state)), offer = createQuestionRoutingOffer(caseFile, state, "请帮我理解这个问题"), context = JSON.stringify(offer.context), body = JSON.stringify(buildQuestionRoutingRequestBody({ enabled: true, endpoint: "https://example.invalid/v1/chat/completions", model: "audit", protocolMode: "strict-schema", keyStorage: "session" }, offer.context)); const leaks = forbidden.filter((token) => token === "query-" ? context.includes(token) || body.includes(token) : projection.includes(token) || context.includes(token) || body.includes(token)); return { caseId: entry.id, publicCandidateCount: offer.context.candidates.length, opaqueTokens: offer.context.candidates.every((item) => /^candidate-\d{2}-[0-9a-f]{4}$/u.test(item.token)), leaks, passed: leaks.length === 0 }; });
function files(dir: string): string[] { return existsSync(dir) ? readdirSync(dir).flatMap((name) => { const path = resolve(dir, name); return statSync(path).isDirectory() ? files(path) : [path]; }) : []; }
const remoteHosts = new Set<string>(); const staticLeaks: Array<{ file: string; token: string }> = [];
for (const path of files(out).filter((item) => [".html", ".js", ".json", ".webmanifest"].includes(extname(item).toLowerCase()))) { const text = readFileSync(path, "utf8"); if (path.endsWith(".html") || path.endsWith(".webmanifest")) for (const match of text.matchAll(/(?:src|href|action)=["'](https?:\/\/[^"']+)/gu)) { try { const url = new URL(match[1]); if (!["localhost", "127.0.0.1"].includes(url.hostname)) remoteHosts.add(url.hostname); } catch { /* ignore malformed strings */ } } if (path.endsWith(".js") && /navigator\.sendBeacon|google-analytics|segment\.io|sentry\.io/iu.test(text)) remoteHosts.add("unexpected-tracker"); for (const token of ["solutionCertificate", "canonicalHypothesisId", "requiredFactIds"]) if (text.includes(token) && path.endsWith(".html")) staticLeaks.push({ file: path.slice(out.length + 1), token }); }
const v18Path = resolve(root, "dist/turtle-soup-v1.8-internal-rc-web-pwa.zip"), v18Sha256 = existsSync(v18Path) ? createHash("sha256").update(readFileSync(v18Path)).digest("hex") : "missing";
const allowedByokHosts = new Set(["api.openai.com"]), unexpectedRemoteHosts = [...remoteHosts].filter((host) => !allowedByokHosts.has(host));
const report = { reportVersion: "1.9", releaseProfile: "v1.9-internal-rc", generatedAt: new Date().toISOString(), status: "internal-rc / human-evaluation-pending", humanParticipants: 0, founderExploratorySessions: 1, cases: projectionChecks, staticLeaks, remoteHosts: [...remoteHosts], unexpectedRemoteHosts, v18Artifact: { expected: "43b6dff6b70abec6a74788bb28fba6f7301eb91dd892818584c82f48fc88d30d", actual: v18Sha256, unchanged: v18Sha256 === "43b6dff6b70abec6a74788bb28fba6f7301eb91dd892818584c82f48fc88d30d" }, boundaries: { truthEngine: "worker-only", aiInput: "public surface + raw question + opaque public candidates", aiDecision: "player-confirmed routing only", apiKeyStorage: "sessionStorage / memory", diagnostics: "aggregate-only", remoteAnalytics: false, remoteByok: "optional / user-configured / default-off" }, passed: projectionChecks.length === 60 && projectionChecks.every((item) => item.passed && item.opaqueTokens) && staticLeaks.length === 0 && unexpectedRemoteHosts.length === 0 && v18Sha256 === "43b6dff6b70abec6a74788bb28fba6f7301eb91dd892818584c82f48fc88d30d" };
writeFileSync(resolve(root, "docs/v1.9-ai-routing-security.json"), `${JSON.stringify(report, null, 2)}\n`, "utf8"); console.log(JSON.stringify({ cases: projectionChecks.length, staticLeaks, remoteHosts: [...remoteHosts], v18Unchanged: report.v18Artifact.unchanged, passed: report.passed }, null, 2)); if (!report.passed) process.exitCode = 1;
