import { createHash } from "node:crypto";
import { existsSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { extname, resolve } from "node:path";
import { createQuestionRoutingOffer, createRuntimeState, projectPlayerState } from "../packages/mystery-core/src/index.ts";
import { buildQuestionRoutingRequestBody } from "../apps/web/lib/question-routing-ai.ts";
import { isAllowedAiEndpoint, isLocalHostEndpoint } from "../apps/web/lib/ai-provider-defaults.ts";
import { loadCaseFile, loadReleaseContent } from "./lib/release-content.ts";

const root = resolve(process.argv[2] ?? "."), out = resolve(root, "apps/web/out"), release = loadReleaseContent(root, "v2.0-internal-rc");
const forbidden = ["solutionCertificate", "canonicalHypothesisId", "requiredFactIds", "alternativeHypothesisIds", "fact-", "query-", "hypothesis-", "apiKey", "authorization", "Bearer "];
const cases = release.entries.map((entry) => { const caseFile = loadCaseFile(entry), state = createRuntimeState(caseFile), projection = JSON.stringify(projectPlayerState(caseFile, state)), offer = createQuestionRoutingOffer(caseFile, state, "请帮我理解这个问题"), context = JSON.stringify(offer.context), body = JSON.stringify(buildQuestionRoutingRequestBody({ enabled: true, endpoint: "https://example.invalid/v1/chat/completions", model: "audit", protocolMode: "strict-schema", keyStorage: "session" }, offer.context)), leaks = forbidden.filter((token) => token === "query-" ? context.includes(token) || body.includes(token) : projection.includes(token) || context.includes(token) || body.includes(token)); return { caseId: entry.id, opaqueTokens: offer.context.candidates.every((item) => /^candidate-\d{2}-[0-9a-f]{4}$/u.test(item.token)), leaks, passed: leaks.length === 0 }; });
function files(dir: string): string[] { return existsSync(dir) ? readdirSync(dir).flatMap((name) => { const path = resolve(dir, name); return statSync(path).isDirectory() ? files(path) : [path]; }) : []; }
const remoteHosts = new Set<string>(), staticLeaks: Array<{ file: string; token: string }> = [];
for (const path of files(out).filter((item) => [".html", ".js", ".json", ".webmanifest"].includes(extname(item).toLowerCase()))) { const source = readFileSync(path, "utf8"); if (path.endsWith(".html") || path.endsWith(".webmanifest")) for (const match of source.matchAll(/(?:src|href|action)=["'](https?:\/\/[^"']+)/gu)) { try { remoteHosts.add(new URL(match[1]).hostname); } catch { /* malformed static URL */ } } if (path.endsWith(".js") && /navigator\.sendBeacon|google-analytics|segment\.io|sentry\.io/iu.test(source)) remoteHosts.add("unexpected-tracker"); for (const token of ["solutionCertificate", "canonicalHypothesisId", "requiredFactIds"]) if (source.includes(token) && path.endsWith(".html")) staticLeaks.push({ file: path.slice(out.length + 1), token }); }
const artifacts = [
  { version: "v1.8", path: "dist/turtle-soup-v1.8-internal-rc-web-pwa.zip", expected: "43b6dff6b70abec6a74788bb28fba6f7301eb91dd892818584c82f48fc88d30d" },
  { version: "v1.9", path: "dist/turtle-soup-v1.9-internal-rc-web-pwa.zip", expected: "c3c074e1170ca2efd7db0b3c0437873dc7d8633074ab4ff4c62c5b7910a8a6fc" },
].map((item) => { const path = resolve(root, item.path), actual = existsSync(path) ? createHash("sha256").update(readFileSync(path)).digest("hex") : "missing"; return { ...item, actual, unchanged: actual === item.expected }; });
const endpointGuards = { remoteHttps: isAllowedAiEndpoint("https://api.openai.com/v1/chat/completions"), remoteHttpRejected: !isAllowedAiEndpoint("http://example.com/v1/chat/completions"), credentialsRejected: !isAllowedAiEndpoint("https://user:secret@example.com/v1/chat/completions"), dangerousPortRejected: !isAllowedAiEndpoint("https://example.com:22/v1/chat/completions"), hostRemoteRejected: !isLocalHostEndpoint("https://example.com/v1/chat/completions"), hostLocalAccepted: isLocalHostEndpoint("http://localhost:11434/v1/chat/completions") };
const serviceWorker = readFileSync(resolve(root, "apps/web/public/sw.js"), "utf8"), serviceWorkerGuards = { sameOriginGetOnly: serviceWorker.includes('event.request.method !== "GET"') && serviceWorker.includes("origin !== self.location.origin"), noRuntimeCachePut: !serviceWorker.includes("cache.put("), queryResponsesNotMatchedAsStatic: serviceWorker.includes("url.search ? undefined"), profileScopedCleanup: serviceWorker.includes("key.startsWith(CACHE_PREFIX)") };
const unexpectedRemoteHosts = [...remoteHosts].filter((host) => host !== "api.openai.com"), passed = cases.length === 60 && cases.every((item) => item.passed && item.opaqueTokens) && staticLeaks.length === 0 && unexpectedRemoteHosts.length === 0 && artifacts.every((item) => item.unchanged) && Object.values(endpointGuards).every(Boolean) && Object.values(serviceWorkerGuards).every(Boolean);
const report = { reportVersion: "2.0", releaseProfile: "v2.0-internal-rc", generatedAt: new Date().toISOString(), status: "internal-rc / human-evaluation-pending", humanParticipants: 0, founderExploratorySessions: 1, cases, staticLeaks, remoteHosts: [...remoteHosts], unexpectedRemoteHosts, artifacts, endpointGuards, serviceWorkerGuards, securityHeaders: "docs/v2.0-deployment-security.md", passed };
writeFileSync(resolve(root, "docs/v2.0-security-scan.json"), `${JSON.stringify(report, null, 2)}\n`, "utf8"); console.log(JSON.stringify({ cases: cases.length, artifacts, endpointGuards, serviceWorkerGuards, passed }, null, 2)); if (!passed) process.exitCode = 1;
