import { createHash } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { loadReleaseContent } from "./lib/release-content.ts";

const root = resolve(process.argv[2] ?? "."), read = <T>(path: string) => JSON.parse(readFileSync(resolve(root, path), "utf8")) as T, exists = (path: string) => existsSync(resolve(root, path));
const profile = read<any>("content/zh/releases/v2.0-internal-rc.json"), current = loadReleaseContent(root, "v2.0-internal-rc"), prior = loadReleaseContent(root, "v1.9-internal-rc"), priorById = new Map(prior.entries.map((entry) => [entry.id, entry]));
const frozen = current.entries.map((entry) => { const old = priorById.get(entry.id); return { caseId: entry.id, canonicalHashUnchanged: old?.canonicalHash === entry.canonicalHash, contentVersionUnchanged: old?.contentVersion === entry.contentVersion, casePathUnchanged: old?.casePath === entry.casePath }; });
const browser = read<any>("docs/v2.0-browser-matrix.json"), visual = read<any>("docs/v2.0-visual-regression.json"), performance = read<any>("docs/v2.0-static-performance.json"), security = read<any>("docs/v2.0-security-scan.json"), save = read<any>("docs/v2.0-save-compatibility.json"), autonomous = read<any>("docs/v2.0-autonomous-experience.json"), dependency = read<any>("docs/v2.0-dependency-audit.json"), artifact = read<any>("docs/v2.0-release-artifacts.json");
const required = ["content/zh/releases/v2.0-internal-rc.json", "docs/v2.0-internal-rc.md", "docs/v2.0-deployment-security.md", "docs/v2.0-browser-matrix.json", "docs/v2.0-visual-regression.json", "docs/v2.0-static-performance.json", "docs/v2.0-security-scan.json", "docs/v2.0-save-compatibility.json", "docs/v2.0-autonomous-experience.json", "docs/v2.0-dependency-audit.json", "docs/v2.0-release-artifacts.json", "dist/turtle-soup-v2.0-internal-rc-web-pwa.zip"];
const hash = (path: string) => exists(path) ? createHash("sha256").update(readFileSync(resolve(root, path))).digest("hex") : "missing";
const gates = { releaseProfile: profile.id === "v2.0-internal-rc" && profile.status === "internal-rc" && profile.publishable === false && profile.humanEvaluation === "pending" && profile.formalFunGateParticipants === 0, caseCatalog: current.entries.length === 60, frozenCompatibility: frozen.length === 60 && frozen.every((item) => item.canonicalHashUnchanged && item.contentVersionUnchanged && item.casePathUnchanged), browser: browser.passed === true && browser.caseCount === 60 && browser.consoleErrorCount === 0 && browser.offlineRecovery?.passed === true, visual: visual.passed === true && visual.contracts?.mobileTheorySteps === true && visual.contracts?.firstMinuteCue === true, performance: performance.passed === true, security: security.passed === true, saveCompatibility: save.passed === true && save.saveSchemaVersion === 1, autonomousExperience: autonomous.passed === true && autonomous.cases?.length === 60, dependencyAudit: dependency.passed === true, artifact: artifact.passed === true && artifact.preservedArtifacts?.every((item: any) => item.unchanged), v18ArtifactUnchanged: hash("dist/turtle-soup-v1.8-internal-rc-web-pwa.zip") === "43b6dff6b70abec6a74788bb28fba6f7301eb91dd892818584c82f48fc88d30d", v19ArtifactUnchanged: hash("dist/turtle-soup-v1.9-internal-rc-web-pwa.zip") === "c3c074e1170ca2efd7db0b3c0437873dc7d8633074ab4ff4c62c5b7910a8a6fc", requiredOutputs: required.every(exists) };
const report = { reportVersion: "2.0", verifiedAt: new Date().toISOString(), releaseProfile: "v2.0-internal-rc", status: "internal-rc / human-evaluation-pending", humanParticipants: 0, founderExploratorySessions: 1, caseCount: current.entries.length, baselineHead: "bb4c81b7d399037693c059d1ada481ca898cf368", frozen, gates, passed: Object.values(gates).every(Boolean), qualification: "v2.0 自动化验证覆盖首分钟导航、手机分步推理、按需模块、BYOK/Service Worker 安全边界、旧存档、三浏览器、离线、性能与反泄漏。正式 Fun Gate 人数仍为 0；不能据此宣称已验证乐趣、审美、理解率、留存或市场适配。" };
writeFileSync(resolve(root, "docs/v2.0-release-verification.json"), `${JSON.stringify(report, null, 2)}\n`, "utf8"); console.log(JSON.stringify({ passed: report.passed, gates }, null, 2)); if (!report.passed) process.exitCode = 1;
