import assert from "node:assert/strict";
import test from "node:test";
import { applyPresentationPatch, presentationPatchHash, validatePresentationPatch } from "./presentation-patch.ts";
import type { CaseFile, CasePresentationPatch } from "./types.ts";

const base = { id: "c25-silent-second-bell", metadata: { canonicalHash: "hash" }, surface: { titleKey: "title", textKey: "surface" }, answerPolicy: { codes: ["yes", "no"], templates: { yes: "是" } }, questionSemantics: [{ id: "q-1", examplePhrases: ["旧标签"] }], evidenceItems: [{ id: "e-1" }], hypotheses: [{ id: "h-1", kind: "alternative" }], chapters: [{ id: "ch-1", titleKey: "old-chapter" }], proofReplay: [{ id: "r-1", eventId: "event-1", factIds: [], captionKey: "old-replay" }], facts: [{ id: "fact-1" }], solutionCertificate: { canonicalHypothesisId: "h-canonical" }, localization: { "zh-CN": { title: "旧标题", surface: "旧谜面" } } } as unknown as CaseFile;
test("presentation patch applies public copy only and fails closed on hash mismatch", () => {
  const patch: CasePresentationPatch = { caseId: base.id, baseCanonicalHash: "hash", presentationRevision: 2, title: "新标题", surface: "新谜面", answerTemplates: { yes: "是。记录支持。" }, questionLabels: { "q-1": "新标签" }, feedbackCopy: { "missing-time": "时间仍未闭合。" }, evidenceCopy: { "e-1": { title: "新证据", observation: "新观察" } }, hypothesisLabels: { "h-1": "新备选路径" }, chapterTitles: { "ch-1": "新章节" }, replayCaptions: { "r-1": "新回放" }, replayChallenges: [{ mode: "limited-questions", questionLimit: 9 }, { mode: "minimal-proof" }, { mode: "no-scaffolds" }] };
  assert.equal(validatePresentationPatch(patch, base).ok, true); const next = applyPresentationPatch(base, patch); assert.equal(next.metadata?.canonicalHash, "hash"); assert.equal(next.localization?.["zh-CN"]?.["__presentation_patch.title"], "新标题"); assert.equal(next.localization?.["zh-CN"]?.["__presentation_patch.feedback.missing-time"], "时间仍未闭合。"); assert.equal(next.answerPolicy.templates?.yes, "是。记录支持。"); assert.equal(next.hypotheses[0].labelKey, "__presentation_patch.hypothesis.h-1"); assert.equal(next.chapters?.[0].titleKey, "__presentation_patch.chapter.ch-1"); assert.equal(next.proofReplay[0].captionKey, "__presentation_patch.replay.r-1"); assert.equal(next.replayChallenges?.length, 3); assert.equal(next.facts, base.facts); assert.equal(next.solutionCertificate, base.solutionCertificate); assert.equal(typeof presentationPatchHash(patch), "string");
  assert.equal(applyPresentationPatch(base, { ...patch, baseCanonicalHash: "wrong" }).surface?.titleKey, "title");
  assert.equal(validatePresentationPatch({ ...patch, replayChallenges: [{ mode: "limited-questions" }, { mode: "limited-questions" }] }, base).ok, false);
});
